uav1:
  id: 1
  x: -22.0
  y: 0.0 
  z: 0.5 
  heading: 0.0

uav2:
  id: 2
  x: -20.0
  y: 3.5
  z: 0.5 
  heading: 0.0
  
uav3:
  id: 3
  x: -16.0
  y: 3.5
  z: 0.5 
  heading: 0.0 

uav4:
  id: 4
  x: -14.0
  y: 0.0
  z: 0.5 
  heading: 0.0 

uav5:
  id: 5
  x: -16.0
  y: -3.5
  z: 0.5 
  heading: 0.0 

uav6:
  id: 6
  x: -20.0
  y: -3.5
  z: 0.5 
  heading: 0.0 

uav7:
  id: 7
  x: -18.0
  y: 0.0
  z: 0.5 
  heading: 0.0 

uav8:
  id: 8
  x: -10.0
  y: 0.0
  z: 0.5 
  heading: 0.0 
